### PR TITLE
Enabled executable bit on binaries run from CLI.

### PR DESCRIPTION
**Pull request by patcon**
Resolves https://github.com/hydrogen-design-system/hydrogen.css/issues/73#

### CODE REVIEW

**Comment by JoshBeveridge** [comment]
@patcon thanks for looking into this. I can't seem to find any changes in your PR though - did you forget to commit or were you just highlighting the files you thought were pertinent?
image

**Comment by JoshBeveridge** [comment]
Oh I see, this is a permissions thing, hence the empty changes.

**Comment by patcon** [comment]
Thanks Josh!

**Comment by patcon** [comment]
Thanks Josh!

**Pull request merged**
