### PR TITLE
Reworks project references to resolve from current directory

### PR DESCRIPTION
**Pull request by JoshBeveridge**
Specifically aimed at resolving the pathing issues outlined in #72

### CODE REVIEW

**Comment by petertgiles** [comment]
Sorry, Josh, I'm still getting errors with this branch.  I'm not certain where the error is being emitted but I think maybe here:
https://github.com/hydrogen-design-system/hydrogen.css/blob/35b918fd71d046ad02890bf5cbbc4957076ef974/lib/scripts/functions/core.js#L132
I've attached my error file:
[h2error.txt](https://github.com/hydrogen-design-system/hydrogen.css/files/7928376/h2error.txt)

**Comment by JoshBeveridge** [comment]
@petertgiles Wow, somehow I missed that function entirely! My apologies Peter. I'll do another sweep and see if I've missed anything else, and push up what I find tonight.

**Comment by petertgiles** [comment]
Nice!  It seems to work for me.  I'm probably only testing a narrow slice of code but so far so good!

**Comment by JoshBeveridge** [comment]
I've addressed every instance of Hydrogen referring to its own library, so theoretically it should cover all cases, but if you run into anything over the course of the day, just shout.

**Pull request merged**
